In [1]:
import numpy as np
import pandas as pd
import matplotlib

In [ ]:
java=[80,70,60,85,90]
db=[75,65,60,80,95]
python=[90,75,70,80,100]

In [ ]:
arr_java=np.array(java)

In [ ]:
print(np.mean(arr_java))
print(arr_java.mean())

In [33]:
score=[java,db,python]
score

[[80, 70, 60, 85, 90], [75, 65, 60, 80, 95], [90, 75, 70, 80, 100]]

In [99]:
arr_score=np.array(score)
#numpy는 [1차원요소,2차원요소] 바로 찾을 수 있다. [start,end,step]
print(arr_score)
print(arr_score[1,2])
print(arr_score[:,2])
print(arr_score[1,:])
print(arr_score[:,::2])
print(np.sum(arr_score))
print(np.sum(arr_score, axis=1)) #1=True y축??
print(np.sum(arr_score, axis=0)) #0=False x축??
print(np.min(arr_score, axis=1))

[[ 80  70  60  85  90]
 [ 75  65  60  80  95]
 [ 90  75  70  80 100]]
60
[60 60 70]
[75 65 60 80 95]
[[ 80  60  90]
 [ 75  60  95]
 [ 90  70 100]]
1175
[385 375 415]
[245 210 190 245 285]
[60 60 70]


In [34]:
print(score[1][1])
#1차원 요소를 먼저 선언해주어야한다
print(score[:][2]) #1차원요소가 없어 [:]를 무시하고 1차원요소 [2]를 찾는다.

65
[90, 75, 70, 80, 100]


In [ ]:
add=[0,0,0,0,0]
for i in range(len(score)):
    for j in range(len(score[i])):
        add[j] += score[i][j]

print(add)

In [ ]:
score=zip(java,db,python)
sum=[]
for i in score:
    add=0
    for j in i:
        add+=j
    sum.append(add)

print(sum)



In [125]:
score2=[java,db,python]
data5=pd.DataFrame(score2)
print(data5)
print(data5.sum(axis=0))
print(data5.sum(axis=1))

    0   1   2   3    4
0  80  70  60  85   90
1  75  65  60  80   95
2  90  75  70  80  100
0    245
1    210
2    190
3    245
4    285
dtype: int64
0    385
1    375
2    415
dtype: int64


In [ ]:
seri=pd.Series(java)
print(seri)
print(seri[::])
print(seri[::2])
print(seri[::-1])
seri.index=['a','b','c','d','e']
print(seri)
seri['a']=100
print(seri)
seri['a':'d']=100
print(seri)

In [74]:
#리스트 그대로 행으로 삽입된다. 우리가 데이터를 볼 때 zip or 딕셔녀리 자료형이 편리하다
df=pd.DataFrame(score)
df

name=['홍길동','노현진','권윤정','강서하','이동관']
data={'name':name,'java':java,'db':db,'python':python}
df=pd.DataFrame(data)
df

name  java  db  python
0  홍길동    80  75      90
1  노현진    70  65      75
2  권윤정    60  60      70
3  강서하    85  80      80
4  이동관    90  95     100

In [45]:
java=[80,70,60,85,90]
db=[75,65,60,80,95]
python=[90,75,70,80,100]
score=[java,db,python]
name=['홍길동','노현진','권윤정','강서하','이동관']
print(score[0])
data1=zip(name,score[0],score[1],score[2])


[80, 70, 60, 85, 90]


In [46]:
df1=pd.DataFrame(data1,
                 columns=['name','java','db','python'],
                 index=['a','b','c','d','e'])


In [58]:
print(df1)
print(df1[['name','python']])
print(df1.db)
df1['add']=df1.java+df1.db+df1.python
df1['avg']=df1['add']/3
print(df1)

  name  java  db  python  add
a  홍길동    80  75      90  245
b  노현진    70  65      75  210
c  권윤정    60  60      70  190
d  강서하    85  80      80  245
e  이동관    90  95     100  285
  name  python
a  홍길동      90
b  노현진      75
c  권윤정      70
d  강서하      80
e  이동관     100
a    75
b    65
c    60
d    80
e    95
Name: db, dtype: int64
  name  java  db  python  add        avg
a  홍길동    80  75      90  245  81.666667
b  노현진    70  65      75  210  70.000000
c  권윤정    60  60      70  190  63.333333
d  강서하    85  80      80  245  81.666667
e  이동관    90  95     100  285  95.000000


In [59]:
df1.name

a    홍길동
b    노현진
c    권윤정
d    강서하
e    이동관
Name: name, dtype: object

In [69]:
#df.loc[행,렬] 행=1차원요소 렬=2차원요소 행과 열을 기준으로 함, 
#열만 보고 싶다하더라도 행에 : 꼭 넣어주여야함! 
#[] 안에 조건식도 가능함!!!!!!!!!

print(df1.loc['a':'c',['name','java']])
print(df1.loc[['a','c'],'name':'python'])
print(df1.loc[:,'name':'db'])
print(df1.loc[df1.avg>=80],['name','avg'])
print(df1.loc[(df1.avg>=80)&(df1.python>=80)],['name','avg'])

  name  java
a  홍길동    80
b  노현진    70
c  권윤정    60
  name  java  db  python
a  홍길동    80  75      90
c  권윤정    60  60      70
  name  java  db
a  홍길동    80  75
b  노현진    70  65
c  권윤정    60  60
d  강서하    85  80
e  이동관    90  95
  name  java  db  python  add        avg
a  홍길동    80  75      90  245  81.666667
d  강서하    85  80      80  245  81.666667
e  이동관    90  95     100  285  95.000000 ['name', 'avg']
  name  java  db  python  add        avg
a  홍길동    80  75      90  245  81.666667
d  강서하    85  80      80  245  81.666667
e  이동관    90  95     100  285  95.000000 ['name', 'avg']


In [71]:
#추가
df1.loc['f',['name','java','db','python']]=['kim',85,75,90]
df1

name  java    db  python    add        avg
a  홍길동  80.0  75.0    90.0  245.0  81.666667
b  노현진  70.0  65.0    75.0  210.0  70.000000
c  권윤정  60.0  60.0    70.0  190.0  63.333333
d  강서하  85.0  80.0    80.0  245.0  81.666667
e  이동관  90.0  95.0   100.0  285.0  95.000000
f  kim  85.0  75.0    90.0    NaN        NaN

In [78]:
print(df)
#iloc는 숫자 일때 사용 3보다 1작은 2까지 max값에서 -1해줌 시작은 0
#컬럼 검색은 렬 숫자로
print(df.iloc[1:3,0:3])
print(df.iloc[[0,2,4],[1,3]])


  name  java  db  python
0  홍길동    80  75      90
1  노현진    70  65      75
2  권윤정    60  60      70
3  강서하    85  80      80
4  이동관    90  95     100
  name  java  db
1  노현진    70  65
2  권윤정    60  60
   java  python
0    80      90
2    60      70
4    90     100


In [82]:
#df1.loc[문자 index, 문자열]
#df1.iloc[숫자 index, 숫자]
df1.iloc[:,0:4]

name  java    db  python
a  홍길동  80.0  75.0    90.0
b  노현진  70.0  65.0    75.0
c  권윤정  60.0  60.0    70.0
d  강서하  85.0  80.0    80.0
e  이동관  90.0  95.0   100.0
f  kim  85.0  75.0    90.0

In [85]:
df2=pd.DataFrame(np.random.randn(6,4))
df2.columns=['A','B','C','D']
df2.index=pd.date_range('20200101',periods=6)
print(df2.index)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')


In [89]:
df1.loc['h',['name','java','db','python']]=['park',85,95,75]
#drop 후 변수에 담아주어야 저장됨 df1은 변함 없음 새로운 객체에 넣어준다!
df3=df1.dropna(how='any')
df3

name  java    db  python    add        avg
a  홍길동  80.0  75.0    90.0  245.0  81.666667
b  노현진  70.0  65.0    75.0  210.0  70.000000
c  권윤정  60.0  60.0    70.0  190.0  63.333333
d  강서하  85.0  80.0    80.0  245.0  81.666667
e  이동관  90.0  95.0   100.0  285.0  95.000000

In [94]:
df1.fillna(value=0.5)
df1
df1.isnull()
df1.loc[df1.isnull()['add'],:]

name  java    db  python  add  avg
f   kim  85.0  75.0    90.0  NaN  NaN
h  park  85.0  95.0    75.0  NaN  NaN

In [104]:
df3=df1.drop(['add','avg'],axis=1) #특정 열 삭제하기
print(df3)
print(df1)

   name  java    db  python
a   홍길동  80.0  75.0    90.0
b   노현진  70.0  65.0    75.0
c   권윤정  60.0  60.0    70.0
d   강서하  85.0  80.0    80.0
e   이동관  90.0  95.0   100.0
f   kim  85.0  75.0    90.0
h  park  85.0  95.0    75.0
   name  java    db  python    add        avg
a   홍길동  80.0  75.0    90.0  245.0  81.666667
b   노현진  70.0  65.0    75.0  210.0  70.000000
c   권윤정  60.0  60.0    70.0  190.0  63.333333
d   강서하  85.0  80.0    80.0  245.0  81.666667
e   이동관  90.0  95.0   100.0  285.0  95.000000
f   kim  85.0  75.0    90.0    NaN        NaN
h  park  85.0  95.0    75.0    NaN        NaN


In [116]:
#df.drop(row or coloumn, 방향 0 :(행방향,x축)or 1 :(열방향,y축))
print(df1)
df4=df1.drop('a') 
print(df4)
print(df)
df4=df.drop(0)
print(df4)

   name  java    db  python    add        avg
a   홍길동  80.0  75.0    90.0  245.0  81.666667
b   노현진  70.0  65.0    75.0  210.0  70.000000
c   권윤정  60.0  60.0    70.0  190.0  63.333333
d   강서하  85.0  80.0    80.0  245.0  81.666667
e   이동관  90.0  95.0   100.0  285.0  95.000000
f   kim  85.0  75.0    90.0    NaN        NaN
h  park  85.0  95.0    75.0    NaN        NaN
   name  java    db  python    add        avg
b   노현진  70.0  65.0    75.0  210.0  70.000000
c   권윤정  60.0  60.0    70.0  190.0  63.333333
d   강서하  85.0  80.0    80.0  245.0  81.666667
e   이동관  90.0  95.0   100.0  285.0  95.000000
f   kim  85.0  75.0    90.0    NaN        NaN
h  park  85.0  95.0    75.0    NaN        NaN
  name  java  db  python
0  홍길동    80  75      90
1  노현진    70  65      75
2  권윤정    60  60      70
3  강서하    85  80      80
4  이동관    90  95     100
  name  java  db  python
1  노현진    70  65      75
2  권윤정    60  60      70
3  강서하    85  80      80
4  이동관    90  95     100


In [128]:

print(df)
print(df.sum(axis=0))
print(df.sum(axis=1))
print(df.mean(axis=0))
print(df.mean(axis=1))
print(df1)
print(df1.sum(axis=1))
print(df1.sum(axis=1,skipna=False))

  name  java  db  python
0  홍길동    80  75      90
1  노현진    70  65      75
2  권윤정    60  60      70
3  강서하    85  80      80
4  이동관    90  95     100
name      홍길동노현진권윤정강서하이동관
java                  385
db                    375
python                415
dtype: object
0    245
1    210
2    190
3    245
4    285
dtype: int64
java      77.0
db        75.0
python    83.0
dtype: float64
0    81.666667
1    70.000000
2    63.333333
3    81.666667
4    95.000000
dtype: float64
   name  java    db  python    add        avg
a   홍길동  80.0  75.0    90.0  245.0  81.666667
b   노현진  70.0  65.0    75.0  210.0  70.000000
c   권윤정  60.0  60.0    70.0  190.0  63.333333
d   강서하  85.0  80.0    80.0  245.0  81.666667
e   이동관  90.0  95.0   100.0  285.0  95.000000
f   kim  85.0  75.0    90.0    NaN        NaN
h  park  85.0  95.0    75.0    NaN        NaN
a    571.666667
b    490.000000
c    443.333333
d    571.666667
e    665.000000
f    250.000000
h    255.000000
dtype: float64
a    571.666667
b    490.0000

In [139]:
print(df1.cumprod)
df1['java']

<bound method DataFrame.cumprod of    name  java    db  python    add        avg
a   홍길동  80.0  75.0    90.0  245.0  81.666667
b   노현진  70.0  65.0    75.0  210.0  70.000000
c   권윤정  60.0  60.0    70.0  190.0  63.333333
d   강서하  85.0  80.0    80.0  245.0  81.666667
e   이동관  90.0  95.0   100.0  285.0  95.000000
f   kim  85.0  75.0    90.0    NaN        NaN
h  park  85.0  95.0    75.0    NaN        NaN>


a    80.0
b    70.0
c    60.0
d    85.0
e    90.0
f    85.0
h    85.0
Name: java, dtype: float64

In [142]:
df=pd.DataFrame(data)
# 상관관계 거의 없음 0.2 중간 0.8 상관관계 밀접
df.java.corr(df.db)
df.java.corr(df.python)

0.853448275862069

In [146]:
df.loc[5]=['lee',10,75,100]
df

name  java  db  python
0  홍길동    80  75      90
1  노현진    70  65      75
2  권윤정    60  60      70
3  강서하    85  80      80
4  이동관    90  95     100
5  lee    10  75     100

In [147]:
df.java.corr(df.db)
df.java.corr(df.python)

-0.2411592955983084

In [148]:
df.java.cov(df.db)

125.0

In [150]:
df['major']=['컴공','컴멀','컴공','정통','정통','컴공']
print(f.groupby(df.major).mean())
print(df.groupby('major').mean())
print(df)


java    db     python
major                       
정통     87.5  87.5  90.000000
컴공     50.0  70.0  86.666667
컴멀     70.0  65.0  75.000000

In [159]:
df.index=['c','a','k','l','b','f']
print(df.sort_index(axis=1)) #y축
print(df.sort_index(axis=0)) #x축
print(df.sort_index(axis=1,ascending=False)) #y축
print(df.sort_index(axis=0,ascending=False)) #x축
#값으로 정렬 (by='필드명')
df.sort_values(by=['java','db'],ascending=False)
df.major.unique()
# column의 각 value 개수 얻기
df.major.value_counts()

   db  java major name  python
c  75    80    컴공  홍길동      90
a  65    70    컴멀  노현진      75
k  60    60    컴공  권윤정      70
l  80    85    정통  강서하      80
b  95    90    정통  이동관     100
f  75    10    컴공  lee     100
  name  java  db  python major
a  노현진    70  65      75    컴멀
b  이동관    90  95     100    정통
c  홍길동    80  75      90    컴공
f  lee    10  75     100    컴공
k  권윤정    60  60      70    컴공
l  강서하    85  80      80    정통
   python name major  java  db
c      90  홍길동    컴공    80  75
a      75  노현진    컴멀    70  65
k      70  권윤정    컴공    60  60
l      80  강서하    정통    85  80
b     100  이동관    정통    90  95
f     100  lee    컴공    10  75
  name  java  db  python major
l  강서하    85  80      80    정통
k  권윤정    60  60      70    컴공
f  lee    10  75     100    컴공
c  홍길동    80  75      90    컴공
b  이동관    90  95     100    정통
a  노현진    70  65      75    컴멀


컴공    3
정통    2
컴멀    1
Name: major, dtype: int64

In [167]:
#지정한 열에 입력한 값이 있는지 확인
df.major.isin(['컴멀'])
df.major.isin(['정통'])
#입력한 값이 있는 행 값
df.loc[df.major.isin(['컴멀']),:]

name  java  db  python major
a  노현진    70  65      75    컴멀

In [168]:
df

name  java  db  python major
c  홍길동    80  75      90    컴공
a  노현진    70  65      75    컴멀
k  권윤정    60  60      70    컴공
l  강서하    85  80      80    정통
b  이동관    90  95     100    정통
f  lee    10  75     100    컴공

In [170]:
#각 열의 최대값
df.max()
df.max(axis=1)

c     90
a     75
k     70
l     85
b    100
f    100
dtype: int64

In [171]:
fnc=lambda x:x.max()-x.min()

In [172]:
def fnc1(x):
    return x.max()-x.min()

In [186]:
#df.apply(fnc,axis=0)
#df['java'].apply(fnc,axis=1)

df5=df[['java','db','python']]
print(df5)
df5.apply(fnc,axis=0)


   java  db  python
c    80  75      90
a    70  65      75
k    60  60      70
l    85  80      80
b    90  95     100
f    10  75     100


java      80
db        35
python    30
dtype: int64